#!/usr/bin/env python3
"""
PR Review Agent - Automated PR review using Claude API

This script reviews GitHub PRs and posts structured review comments.
"""

import os
import sys
import json
import subprocess
import argparse
import re
from typing import Optional, Dict, Any
import requests
from dataclasses import dataclass


@dataclass
class Config:
    """Configuration for the PR review agent"""
    api_key: str
    model: str = "claude-3-5-sonnet-20241022"
    api_url: str = "https://api.anthropic.com/v1/messages"
    max_diff_size: int = 500000  # ~500KB max diff size
    review_focus: str = "general"  # general, security, performance, readability
    verbose: bool = False


def log(msg: str, verbose: bool = False):
    """Print message if verbose mode is enabled"""
    if verbose:
        print(f"[PR-REVIEW] {msg}")


def run_gh_command(args: list, verbose: bool = False) -> tuple[str, str, int]:
    """Run a gh CLI command and return stdout, stderr, returncode"""
    cmd = ["gh"] + args
    log(f"Running: {' '.join(cmd)}", verbose)
    
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout, result.stderr, result.returncode


def parse_pr_url(url: str) -> Dict[str, str]:
    """Parse GitHub PR URL to extract owner, repo, and PR number"""
    patterns = [
        r"github\.com/([^/]+)/([^/]+)/pull/(\d+)",
        r"github\.com/([^/]+)/([^/]+)/pulls/(\d+)",
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return {
                "owner": match.group(1),
                "repo": match.group(2),
                "pr_number": match.group(3)
            }
    
    raise ValueError(f"Invalid PR URL format: {url}")


def fetch_pr_diff(owner: str, repo: str, pr_number: str, verbose: bool = False) -> str:
    """Fetch the diff for a PR using gh CLI"""
    stdout, stderr, returncode = run_gh_command(
        ["pr", "diff", f"{owner}/{repo}#{pr_number}", "--patch"],
        verbose
    )
    
    if returncode != 0:
        raise RuntimeError(f"Failed to fetch PR diff: {stderr}")
    
    return stdout


def fetch_pr_metadata(owner: str, repo: str, pr_number: str, verbose: bool = False) -> Dict[str, Any]:
    """Fetch PR metadata (title, description, etc.)"""
    stdout, stderr, returncode = run_gh_command(
        ["pr", "view", f"{owner}/{repo}#{pr_number}", "--json", "title,body,author,baseRefName,headRefName,files"],
        verbose
    )
    
    if returncode != 0:
        log(f"Warning: Could not fetch PR metadata: {stderr}", verbose)
        return {}
    
    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        log(f"Warning: Could not parse PR metadata", verbose)
        return {}


def get_review_prompt(review_focus: str) -> str:
    """Get the system prompt based on review focus"""
    base_prompt = """You are an expert code reviewer. Analyze the provided PR diff and metadata, then provide a structured review.

Your review must be in this exact markdown format:

## Summary
[Brief 2-3 sentence summary of what this PR changes]

## Potential Issues
[List any bugs, logical errors, or potential runtime issues found]
- [Issue 1]
- [Issue 2]
(Use "None identified" if no issues found)

## Suggestions for Improvement
[Specific, actionable suggestions to improve the code]
- [Suggestion 1]
- [Suggestion 2]

## Security Considerations
[Any security-related concerns or recommendations]
- [Security point 1]
- [Security point 2]

## Code Quality
[Overall assessment of code quality, maintainability, and best practices]

---
*Review generated by Claude Code PR Review Agent*"""

    focus_additions = {
        "security": "\n\nPay special attention to: SQL injection, XSS, CSRF, authentication/authorization issues, sensitive data exposure, insecure dependencies, and input validation.",
        "performance": "\n\nPay special attention to: Time complexity, memory usage, database query optimization, caching opportunities, and resource leaks.",
        "readability": "\n\nPay special attention to: Code clarity, naming conventions, documentation, code organization, and adherence to style guides.",
        "general": ""
    }
    
    return base_prompt + focus_additions.get(review_focus, "")


def review_with_claude(config: Config, diff: str, metadata: Dict[str, Any]) -> str:
    """Send diff to Claude API for review"""
    if len(diff) > config.max_diff_size:
        raise RuntimeError(
            f"PR diff too large ({len(diff)} bytes > {config.max_diff_size} bytes). "
            "Consider reviewing in smaller chunks."
        )
    
    # Build the user message with diff and metadata
    user_message = f"Please review this pull request:\n\n"
    
    if metadata:
        user_message += f"**PR Title:** {metadata.get('title', 'N/A')}\n"
        user_message += f"**Author:** {metadata.get('author', {}).get('login', 'N/A')}\n"
        user_message += f"**Branch:** {metadata.get('headRefName', 'N/A')} → {metadata.get('baseRefName', 'N/A')}\n"
        if metadata.get('body'):
            user_message += f"\n**Description:**\n{metadata['body']}\n"
        user_message += "\n---\n\n"
    
    user_message += f"**Diff:**\n```diff\n{diff}\n```"
    
    headers = {
        "Content-Type": "application/json",
        "x-api-key": config.api_key,
        "anthropic-version": "2023-06-01"
    }
    
    payload = {
        "model": config.model,
        "max_tokens": 4096,
        "system": get_review_prompt(config.review_focus),
        "messages": [
            {
                "role": "user",
                "content": user_message
            }
        ]
    }
    
    log(f"Sending review request to Claude API (model: {config.model})", config.verbose)
    
    try:
        response = requests.post(
            config.api_url,
            headers=headers,
            json=payload,
            timeout=60
        )
        response.raise_for_status()
        
        result = response.json()
        return result["content"][0]["text"]
    
    except requests.exceptions.Timeout:
        raise RuntimeError("Claude API request timed out")
    except requests.exceptions.HTTPError as e:
        raise RuntimeError(f"Claude API error: {e.response.status_code} - {e.response.text}")
    except (KeyError, IndexError) as e:
        raise RuntimeError(f"Unexpected Claude API response format: {e}")


def post_review_comment(owner: str, repo: str, pr_number: str, comment: str, verbose: bool = False) -> bool:
    """Post the review comment on the PR using gh CLI"""
    # Save comment to a temp file to avoid shell escaping issues
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
        f.write(comment)
        temp_file = f.name
    
    try:
        stdout, stderr, returncode = run_gh_command(
            ["pr", "comment", f"{owner}/{repo}#{pr_number}", "--body-file", temp_file],
            verbose
        )
        
        if returncode != 0:
            log(f"Error posting comment: {stderr}", verbose)
            return False
        
        log(f"Successfully posted review comment", verbose)
        return True
    finally:
        os.unlink(temp_file)


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description="Automated PR review using Claude API"
    )
    parser.add_argument(
        "pr_url",
        help="GitHub PR URL (e.g., https://github.com/owner/repo/pull/123)"
    )
    parser.add_argument(
        "--api-key",
        help="Anthropic API key (defaults to ANTHROPIC_API_KEY env var)",
        default=os.environ.get("ANTHROPIC_API_KEY")
    )
    parser.add_argument(
        "--model",
        default="claude-3-5-sonnet-20241022",
        help="Claude model to use for review (default: claude-3-5-sonnet-20241022)"
    )
    parser.add_argument(
        "--focus",
        choices=["general", "security", "performance", "readability"],
        default="general",
        help="Review focus area (default: general)"
    )
    parser.add_argument(
        "--max-diff-size",
        type=int,
        default=500000,
        help="Maximum diff size in bytes (default: 500000)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate review without posting to PR"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging"
    )
    
    args = parser.parse_args()
    
    # Validate API key
    if not args.api_key:
        print("Error: API key required. Set ANTHROPIC_API_KEY env var or use --api-key", file=sys.stderr)
        sys.exit(1)
    
    # Create config
    config = Config(
        api_key=args.api_key,
        model=args.model,
        max_diff_size=args.max_diff_size,
        review_focus=args.focus,
        verbose=args.verbose
    )
    
    try:
        # Parse PR URL
        log(f"Parsing PR URL: {args.pr_url}", args.verbose)
        pr_info = parse_pr_url(args.pr_url)
        log(f"PR: {pr_info['owner']}/{pr_info['repo']}#{pr_info['pr_number']}", args.verbose)
        
        # Fetch PR metadata
        log("Fetching PR metadata...", args.verbose)
        metadata = fetch_pr_metadata(
            pr_info["owner"],
            pr_info["repo"],
            pr_info["pr_number"],
            args.verbose
        )
        
        # Fetch PR diff
        log("Fetching PR diff...", args.verbose)
        diff = fetch_pr_diff(
            pr_info["owner"],
            pr_info["repo"],
            pr_info["pr_number"],
            args.verbose
        )
        
        if not diff.strip():
            print("Warning: Empty diff retrieved from PR", file=sys.stderr)
        
        # Review with Claude
        log("Sending to Claude for review...", args.verbose)
        review = review_with_claude(config, diff, metadata)
        
        # Output review
        print("\n" + "="*80)
        print("REVIEW GENERATED:")
        print("="*80 + "\n")
        print(review)
        print("\n" + "="*80 + "\n")
        
        # Post comment (unless dry-run)
        if args.dry_run:
            log("Dry-run mode: skipping comment post", args.verbose)
            print("Review generated but not posted (dry-run mode)")
        else:
            log("Posting review comment...", args.verbose)
            success = post_review_comment(
                pr_info["owner"],
                pr_info["repo"],
                pr_info["pr_number"],
                review,
                args.verbose
            )
            
            if success:
                print(f"✓ Review posted successfully to {args.pr_url}")
                sys.exit(0)
            else:
                print(f"✗ Failed to post review comment", file=sys.stderr)
                sys.exit(1)
    
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nInterrupted by user", file=sys.stderr)
        sys.exit(130)
    except Exception as e:
        print(f"Unexpected error: {e}", file=sys.stderr)
        if args.verbose:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
